server:
  port: 8082


spring:
  cloud:
    gateway:
      routes:
        - id: employeeModule
          uri: http://localhost:8080/
          predicates:
            - Path=/employee/**
        - id: consumerModule
          uri: http://localhost:8081/
          predicates:
            - Path=/consumer/**